sudo: required
services:
  - docker

before_install:
  - docker build -t hayaten0415/docker-practice -f Dockerfile.dev .

script:
  - docker run hayaten0415/docker-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-practice"
  env: "DockerPractice-env"
  bucket_name: "elasticbeanstalk-us-west-2-422754132200"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
